name:                weather-api
version:             0.1.0.0
license:             BSD3

ghc-options:
  - -Wall

dependencies:
- base >= 4.7 && < 5
- warp
- servant
- servant-server
- servant-flatten
- mtl
- postgresql-simple
- uuid
- aeson

library:
  source-dirs: src

executables:
  weather-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - weather-api

tests:
  weather-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - weather-api
